<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\TestMap.bmp" />
    <None Remove="Synk Gaming.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\TestMap.bmp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="View\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Synk Gaming.png" />
  </ItemGroup>

</Project>
